artifact_location: file:C:/Users/Héctor/OneDrive/Desktop/Projects/EFREI/M1-DE/ML-DL/tri_radio_DL/mlruns_quick/992113820138064591
creation_time: 1780141506569
experiment_id: '992113820138064591'
last_update_time: 1780141506569
lifecycle_stage: active
name: tri_radiologique_chestmnist_quick
trace_location: null
workspace: default
