artifact_location: file:C:/Users/Héctor/OneDrive/Desktop/Projects/EFREI/M1-DE/ML-DL/tri_radio_DL/mlruns_openi_multimodal/870401291389657308
creation_time: 1780149064502
experiment_id: '870401291389657308'
last_update_time: 1780149064502
lifecycle_stage: active
name: openi_multimodal_official
trace_location: null
workspace: default
