artifact_location: file:C:/Users/Héctor/OneDrive/Desktop/Projects/EFREI/M1-DE/ML-DL/tri_radio_DL/mlruns_final/377715742807753371
creation_time: 1780164179144
experiment_id: '377715742807753371'
last_update_time: 1780164179144
lifecycle_stage: active
name: tri_radiologique_final
trace_location: null
workspace: default
