artifact_location: file:C:/Users/Héctor/OneDrive/Desktop/Projects/EFREI/M1-DE/ML-DL/tri_radio_DL/mlruns_openi_text/619480377239562558
creation_time: 1780142216632
experiment_id: '619480377239562558'
last_update_time: 1780142216632
lifecycle_stage: active
name: openi_text_official
trace_location: null
workspace: default
