artifact_location: file:C:/Users/Héctor/OneDrive/Desktop/Projects/EFREI/M1-DE/ML-DL/tri_radio_DL/mlruns_openi_text/0
creation_time: 1780142216611
experiment_id: '0'
last_update_time: 1780142216611
lifecycle_stage: active
name: Default
trace_location: null
workspace: default
