artifact_uri: file:C:/Users/Héctor/OneDrive/Desktop/Projects/EFREI/M1-DE/ML-DL/tri_radio_DL/mlruns_quick/992113820138064591/c178b7c01b674e03b717bcc084a93d8a/artifacts
end_time: 1780141570842
entry_point_name: ''
experiment_id: '992113820138064591'
lifecycle_stage: active
run_id: c178b7c01b674e03b717bcc084a93d8a
run_name: chestmnist_vit
source_name: ''
source_type: 4
source_version: ''
start_time: 1780141565937
status: 3
tags: []
user_id: Héctor
